Added getacqinfo / getfileinfo functions for HFB acquisitions.
chime-experiment/alpenhorn pull request #9
Opened 2021-02-18 18:42 UTC by james-s-willis

2021-02-18 18:43 UTC, james-s-willis commented
@ketiltrout is there a way to test this before merging?

2021-02-23 23:27 UTC, ketiltrout requested changes
There seems to be confusion here over whether HFB files are `corr` files or something new.

You're adding entries to `CorrAcqInfo` here but over in https://github.com/chime-experiment/chimedb_di/pull/14 you've defined new HFB-specific tables.

So, definitely step one is to figure out whether HFB files are `corr` files or not.

If they're not, you'll also need to define them in the acq_format file before this PR can be approved.  The TeX for that is over here and the document provides instructions on the procedure for updating itself: https://github.com/chime-experiment/ch_memos/blob/master/acq_format/acq_format.tex

The PDF version of the acq format document is in doclib: https://bao.chimenet.ca/doc/documents/5

2021-02-23 23:27 UTC, ketiltrout commented on alpenhorn/auto_import.py
> +                    'Added information for correlator acquisition "%s" to '
```suggestion
                    'Added information for HFB acquisition "%s" to '
```
"Correlator" refers to the `corr` file type in this case

2021-02-23 23:27 UTC, ketiltrout commented on alpenhorn/auto_import.py
> +                di.CorrAcqInfo.create(
```suggestion
                di.HFBAcqInfo.create(
```
(and throughout).  The `CorrAcqInfo` table is for files of type `corr`.

2021-02-23 23:27 UTC, ketiltrout commented on alpenhorn/auto_import.py
> +                di.CorrAcqInfo.create(acq=acq)
```suggestion
                di.HFBAcqInfo.create(acq=acq)
```

2021-02-23 23:27 UTC, ketiltrout commented on alpenhorn/auto_import.py
> +def get_filehfbinfo_keywords_from_h5(path):
This function is never called.

You probably intended to call it before creating a new `HKPFileInfo` entry as part of the big if-elif clause down around here https://github.com/chime-experiment/alpenhorn/blob/e4685ef8dd42040f49960edc8f84ba1ee8cce7dd/alpenhorn/auto_import.py#L810

2021-02-23 23:27 UTC, ketiltrout commented on alpenhorn/auto_import.py
> +def get_acqhfbinfo_keywords_from_h5(path):
This function is never called.

Presumably you want to call it before creating the new `HFBAcqInfo` entry below to get the data to populate the new record with.

Down here: https://github.com/chime-experiment/alpenhorn/blob/e4685ef8dd42040f49960edc8f84ba1ee8cce7dd/alpenhorn/auto_import.py#L536

2021-02-23 23:27 UTC, ketiltrout commented on alpenhorn/auto_import.py
> +    if atype == "hfb" and ftype.name == "hfb":
```suggestion
    elif atype == "hfb" and ftype.name == "hfb":
```
This is part of one big if-elif statement running though all the acq types

2021-02-24 00:41 UTC, jrs65 commented
@james-s-willis as Don says you'll also need to create a new hfb acq type for this. The corr acq type is to hold visibility correlation (which these are not).

2021-02-26 16:00 UTC, james-s-willis commented
https://github.com/chime-experiment/alpenhorn/blob/2796cfd97db32346fd4a00132f57f6e5cda87cea/alpenhorn/auto_import.py#L589
I know I'm not editing this part, but shouldn't this line have `file.hkinfos.count()` instead of `corrinfos`?

2021-02-26 18:25 UTC, james-s-willis commented
@ketiltrout, @jrs65 I have updated this PR with your corrections and I have created a new PR (https://github.com/chime-experiment/ch_memos/pull/4) for the HFB acq type in the CHIME Archive Data Format document.

2021-03-09 22:20 UTC, ketiltrout commented
> I know I'm not editing this part, but shouldn't this line have `file.hkinfos.count()` instead of `corrinfos`? @ketiltrout

More amazingness from this code.  You're right, and I made an issue for it, but really it looks like that `if` should be deleted and the `except` line above should be fixed so it only catches the exception thrown if the update fails, not everything.

2021-03-09 22:24 UTC, ketiltrout approved these changes

2021-03-10 20:38 UTC, merged